### PR TITLE
Add "API Docs" GitHub Action to check if docs are up to date

### LINKED ISSUE #311: Docs generation failing in CI pipeline
```
Run git push origin main
remote: error: GH006: Protected branch update failed for refs/heads/main.        
remote: error: 5 of 5 required status checks are expected. Waiting on code owner review from jonathan-innis and/or nitishm.        
To https://github.com/Azure/orkestra
 ! [remote rejected] main -> main (protected branch hook declined)
error: failed to push some refs to 'https://github.com/Azure/orkestra'
Error: Process completed with exit code 1.
```
, from https://github.com/Azure/orkestra/runs/2806983566?check_suite_focus=true

@mahalrs

### PR DESCRIPTION
**Pull request by mahalrs**
Closes: #311

This change add a GitHub Action to check if API docs are up to date. If not, this check will fail and you should run `make api-docs` before pushing your changes (similar to golangci lint check).

**NOTE 1:**

Since the main branch is protected, Github action cannot use regular GITHUB_TOKEN, it needs special privileges. But if we create a Personal Access Token with write access, any collaborator can make changes to the workflow and can misuse the token.

>  https://github.community/t/how-to-push-to-protected-branches-in-a-github-action/16101/5
The token will not be able to push to a protected branch as that would enable anyone with write access to your repo to push to that protected branch by simply updating the workflow in a branch. Having that ability would make protected branches useless.

So we should create a required check (similar to e2e, golangci-lint) to see if api docs are up to date.  If not, this check will fail and the person making the PR (or pushing directly to main) should run `make api-docs` to update the docs before pushing/merging changes.

@nitishm @jonathan-innis Let me know if you have any suggestions such as if there is a way collaborators can't misuse the token by making changes to workflow action.

**NOTE 2:**

This check will fail because I have added a line to ./docs/api.md that makes docs outdated. So, I must run `make api-docs` and push new changes to pass all checks.

**EDIT:** Updated api docs by running `make api-docs` locally and committed new changes. Now API Docs check should pass.

### CODE REVIEW

**Review by nitishm — COMMENTED** [review]
Makes sense to me!

**Comment by nitishm** [comment]
@mahalrs We should add this step to contributors/developers docs as well

**Comment by mahalrs** [comment]
> @mahalrs We should add this step to contributors/developers docs as well

You mean checking if contributors/developers docs are up to date OR adding a note to contributors/developers docs that they must run `make api-docs` before pushing changes.

**Comment by nitishm** [comment]
> > @mahalrs We should add this step to contributors/developers docs as well
> 
> You mean checking if contributors/developers docs are up to date OR adding a note to contributors/developers docs that they must run `make api-docs` before pushing changes.

The latter

**Comment by mahalrs** [comment]
> > > @mahalrs We should add this step to contributors/developers docs as well
> > 
> > 
> > You mean checking if contributors/developers docs are up to date OR adding a note to contributors/developers docs that they must run `make api-docs` before pushing changes.
> 
> The latter

Done

**Review by nitishm — APPROVED** [review]
Looks awesome!

**Pull request merged**
