### PR TITLE
Remove Checksum in Favor of Generation Comparison

### LINKED ISSUE #148: Change Checksum logic to use Predicates/Event Filters
Just a "cleanup" item. We can improve our controller logic by adding event filters like:
```
return ctrl.NewControllerManagedBy(mgr).
	For(&appGroup{}).
	WithEventFilter(predicate.GenerationChangedPredicate{}).
	Complete(r)
```
rather than doing custom logic with checksums on the spec as is done here
```
// handle first time install and subsequent updates
checksums, err := api.Checksum(&appGroup)
```

### PR DESCRIPTION
**Pull request by jonathan-innis**
- Removes the need to calculate the checksum value of the spec by comparing the current generation of the spec to the previously updated generation of the spec

Closes #148

### CODE REVIEW

**Comment by jonathan-innis** [comment]
Closes #148

**Comment by nitishm** [comment]
This is excellent!
Will try this out locally and then merge it! 
Great job @jonathan-innis 🎉

**Comment by jonathan-innis** [comment]
> This is excellent!
> Will try this out locally and then merge it!
> Great job @jonathan-innis 🎉

I'm not sure if the `spec.status.checksum` was originally intended to capture the checksum of the underlying `application.spec` but right now it seems to only be capturing the checksum of the application group spec

**Comment by nitishm** [comment]
I think any specific change should lead to a reconcile and recreation of workflow to perform the upgrade against the relevant HelmRelease

**Comment by jonathan-innis** [comment]
> I think any spec change should lead to a reconcile and recreation of workflow to perform the upgrade against the relevant HelmRelease

In that case, this is captured correctly with the changes

**Review by nitishm — APPROVED** [review]

**Pull request merged**
