### PR TITLE
correct coding convention#patched

### LINKED ISSUE #369: Log the error message during helm repo add
https://github.com/Azure/orkestra/blob/47d8dc34e498cf519ea0c89d8dbb80febaf20479/main.go#L138

### PR DESCRIPTION
**Pull request by linhbkhn95**
why do we need it?
- correct log error
- correct coding convention

closes #369

### CODE REVIEW

**Review by nitishm — APPROVED** [review]
Thanks for the PR. This looks great! 🎉🎉

**Comment by linhbkhn95** [comment]
@nitishm tks bro, I want to contribute many more to the project.

**Comment by nitishm** [comment]
> @nitishm tks bro, I want to contribute many more to the project.

Of course! We are looking for more contributors. Feel free to pick up any task from the issues list and let me know. Also do join the slack channel and we can chat and discuss the details there.

**Comment by linhbkhn95** [comment]
@nitishm please send me link that join slack channel to email trinhducbaolinh@gmail.com

**Comment by nitishm** [comment]
> @nitishm please send me a link that joins the slack channel to email trinhducbaolinh@gmail.com

Sent

**Pull request merged**
